### ISSUE TITLE
(payment) test checkout.com api if it's working

### ISSUE THREAD

**Issue by kevinchua6** [Project-Juniors-Club/jc-app#10]
| Current    | Expected |
| -------- | ------- |
| existing pr on payment #191   | PayNow and Credit Card option to pay should work. <img width="590" alt="Screenshot 2024-06-02 at 12 35 41 AM" src="https://github.com/Project-Juniors-Club/jc-app/assets/96589109/8d5bf2e4-38a6-41e5-b0d3-237828587949"> <img width="582" alt="Screenshot 2024-06-02 at 12 36 43 AM" src="https://github.com/Project-Juniors-Club/jc-app/assets/96589109/fa7cd976-cd52-431c-bece-c0a474c80ab1"> <img width="660" alt="Screenshot 2024-06-01 at 11 24 30 PM" src="https://github.com/Project-Juniors-Club/jc-app/assets/96589109/b897d276-c96d-41df-be4c-1c6424e69d53">|

**Comment by miloaisdino** [comment]
feature cancelled
