### ISSUE TITLE
View Cart

### ISSUE THREAD

**Issue by kevinchua6** [Project-Juniors-Club/jc-app#102]
![image](https://user-images.githubusercontent.com/45702380/199263798-fed379fb-8798-44e0-a343-1b30df04bc92.png)

**Comment by kxrt** [comment]
<img width="718" alt="Screenshot 2022-12-20 at 2 28 59 PM" src="https://user-images.githubusercontent.com/73589885/208626046-af4dd2a7-49a5-4130-a06d-b9081722060e.png">
