### ISSUE TITLE
Add Formik library to project

### ISSUE THREAD

**Issue by yunpeng1234** [Project-Juniors-Club/jc-app#18]
Form validation for create account any further forms

**Comment by kevinchua6** [comment]
Formik discontinued, @MorningLit please help to find an alternative package, thanks!

![IMAGE 2022-09-04 17:28:54](https://user-images.githubusercontent.com/45702380/188306829-34cb0883-60aa-4d93-9835-fa91c2a54c25.jpg)

**Comment by MorningLit** [comment]
react-hook-form looks like a solid package https://react-hook-form.com/
