### ISSUE TITLE
image in course list does not appear

### ISSUE THREAD

**Issue by kevinchua6** [Project-Juniors-Club/jc-app#195]

**Comment by sltsheryl** [comment]
Images uploaded aren't displayed

![image](https://github.com/Project-Juniors-Club/jc-app/assets/96589109/7a786ce6-d582-4d69-8560-1ca9cbf42775)

**Comment by yunpeng1234** [comment]
![image](https://github.com/Project-Juniors-Club/jc-app/assets/58326594/9db53bf8-dda4-447b-8d6b-cefd9ffdd3ec)


Fixed by adjust policy to handle .jpeg extensions
