### ISSUE TITLE
staff transaction management

### ISSUE THREAD

**Issue by sltsheryl** [Project-Juniors-Club/jc-app#219]
| Current    | Expected |
| -------- | ------- |
| Not implemented. (frontend/ backend not done)  |  Add transaction table to the db to keep track when users check out of cart. View list of transactions <img width="850" alt="Screenshot 2024-01-09 at 9 00 43 PM" src="https://github.com/Project-Juniors-Club/jc-app/assets/96589109/495bd660-6c0d-4d1a-bb6a-f79b5cf29b1a">    |

**Comment by miloaisdino** [comment]
cancel feature
