### ISSUE TITLE
feat: payment route after checkout is not dynamic + add to user courses backend

### ISSUE THREAD

**Issue by sltsheryl** [Project-Juniors-Club/jc-app#239]
| Current    | Expected |
| -------- | ------- |
| It's a fixed payment page. (Courses name is hard coded)  <img width="1349" alt="Screenshot 2024-06-01 at 11 19 32 PM" src="https://github.com/Project-Juniors-Club/jc-app/assets/96589109/47fa7930-6f1f-43fa-8e85-5093304bfb92">  | 1. Should be based on what the user is purchasing in the current session. <br> 2. BE differentiate whether a user owns the course - add to userCourses once payment is done <br> 3. User learning page should only consist of purchased courses.  It should be added to the model `userCourses` I believe|

**Comment by miloaisdino** [comment]
feature removed
