### ISSUE TITLE
Delete account UI

### ISSUE THREAD

**Issue by remuskwan** [Project-Juniors-Club/jc-app#56]
- [x] Prompt user for password before allowed to delete account
- [x] Send email to customer after account is deleted
- [x] Customer no longer able to log in

**Comment by sltsheryl** [comment]
<img width="302" alt="Screenshot 2023-12-07 at 9 18 12 PM" src="https://github.com/Project-Juniors-Club/jc-app/assets/96589109/36f432cc-86ba-4e03-a4cc-88a39ee9173c">
