### ISSUE TITLE
Add Course to Cart (General Users)

### ISSUE THREAD

**Issue by BryannYeap** [Project-Juniors-Club/jc-app#78]
- [x] Users can add course to cart (both FrontEnd) 
- [x] Add to cart BackEnd so that when users log back in their cart is still filled
- [x] Visual indicator to show items added to cart (like a pop up or some text, TBD by UI/UX team)
- [ ] Cart icon updated to show number of items in cart
- [ ] In the case that there are minimum requirements of the Course that is not met, disable the add to cart button

**Comment by sltsheryl** [comment]
Related to #211
