### ISSUE TITLE
Working create account page 

### ISSUE THREAD

**Issue by kevinchua6** [Project-Juniors-Club/jc-app#9]

**Comment by remuskwan** [comment]
To add
- [ ] Name field
- [ ] Age field
- [ ] PDPA consent
- [ ] Click Signup button to be redirected to signup page
- [ ] Verification email sent on form submission

To remove
- [ ] Confirm password field (according to requirements)

To change
- [ ] Follow validation in requirements
<img width="653" alt="Screenshot 2022-10-04 at 8 23 50 PM" src="https://user-images.githubusercontent.com/36059985/193818351-6f8dd319-aa0e-43f9-9aad-ad7d3e6b5ce2.png">
